### ISSUE TITLE
Inquiry and Appreciation for Your Paper's Demo

### ISSUE THREAD

**Issue by Learner4AI** [8erberg/spatially-embedded-RNN#1]
Hi there, I wanted to express my gratitude for your significant contributions, especially the release of the demo code, which has been immensely helpful in understanding and implementing the concepts outlined in your research.

I am currently exploring the fascinating work you presented in your paper. While experimenting with the demo, I encountered a challenge related to the reproduction of specific results. Specifically, I am having difficulty achieving the same outcomes as those presented in the paper for metrics such as "total weight over training epochs," "Network modularity over training," and "Network small worldness over training." Despite following the provided instructions meticulously, my results seem to deviate from the expected trends outlined in your work.

I wanted to reach out to inquire if you could provide any insights or additional details that might help align my outcomes with the reported findings. Any guidance you can offer would be greatly appreciated.

The following is my results:
[myresults.pdf](https://github.com/8erberg/spatially-embedded-RNN/files/13629883/myresults.pdf)

Looking forward to your reply. Thank you again.

**Comment by 8erberg** [comment]
Hi @Learner4AI ! 

Thank you so much for your interest in our project! I am very sorry that this reply is slightly delayed. Regarding your question, I assume you are basing your result on the spiking version of the network, i.e. https://github.com/8erberg/spatially-embedded-RNN/blob/main/seRSNN_demo.ipynb ? 

First, I should note that our recent paper (https://www.nature.com/articles/s42256-023-00748-9) is based on the rate based model (https://github.com/8erberg/spatially-embedded-RNN/blob/main/seRNN_demo.ipynb). I did check and this demo still works as expected and we also provide a stable environment with this demo at https://codeocean.com/capsule/2879348/tree/v2 if you struggle replicating any results with regards to the paper. The spiking version that you seem to be using is an experimental versions which we are building for future work. Non of the results in the paper are based on the spiking version.

To directly comment on your issue of not being able to replicate the plots in the spiking network notebook: We did run a quick test on this ourselves last week and you are right that running this notebook on Colab right now does show different results. We do have running versions of this on our department cluster as part of ongoing investigations where the results do replicate, so it likely is related to a change in the baseline package version provided by Colab at the current point in time. We will update the notebook with the correct Python package versions as soon as possible. 

Thank you again for raising this issue!

**Comment by Learner4AI** [comment]
> Hi @Learner4AI !
> 
> Thank you so much for your interest in our project! I am very sorry that this reply is slightly delayed. Regarding your question, I assume you are basing your result on the spiking version of the network, i.e. https://github.com/8erberg/spatially-embedded-RNN/blob/main/seRSNN_demo.ipynb ?
> 
> First, I should note that our recent paper (https://www.nature.com/articles/s42256-023-00748-9) is based on the rate based model (https://github.com/8erberg/spatially-embedded-RNN/blob/main/seRNN_demo.ipynb). I did check and this demo still works as expected and we also provide a stable environment with this demo at https://codeocean.com/capsule/2879348/tree/v2 if you struggle replicating any results with regards to the paper. The spiking version that you seem to be using is an experimental versions which we are building for future work. Non of the results in the paper are based on the spiking version.
> 
> To directly comment on your issue of not being able to replicate the plots in the spiking network notebook: We did run a quick test on this ourselves last week and you are right that running this notebook on Colab right now does show different results. We do have running versions of this on our department cluster as part of ongoing investigations where the results do replicate, so it likely is related to a change in the baseline package version provided by Colab at the current point in time. We will update the notebook with the correct Python package versions as soon as possible.
> 
> Thank you again for raising this issue!

Hi @8erberg,

Thank you very much for your detailed response. I appreciate your clarification regarding the rate-based model and the experimental spiking version. 

I understand that the spiking version is experimental, and I appreciate your transparency about its ongoing development. I'll keep an eye out for updates on the notebook, and I'm grateful for your commitment to addressing these issues.

Your work is truly fascinating, and I look forward to following the progress of your research and any updates on the spiking version.

Thank you so much.

**Comment by 8erberg** [comment]
I just wanted to update that we now concluded additional investigations on the spiking version which can be found here: https://arxiv.org/abs/2409.17693

Alongside these investigations we did now also fix the demo hosted in the repository: https://github.com/8erberg/spatially-embedded-RNN/blob/main/seRSNN_demo.ipynb
