### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by nshervt** [8erberg/spatially-embedded-RNN#2]
Hello, 

I have a question regarding the data generator in your repository. I noticed that you defined eight possible scenarios for the combination of goals and choices, i.e.,
```
self.mazesDic = {'goal': {0: 9, 1: 9, 2: 19, 3: 17, 4: 17, 5: 7, 6: 19, 7: 7},
                            'ChoicesCategory': {0: 'ul', 1: 'rd', 2: 'ld', 3: 'rd', 4: 'ul', 5: 'ur', 6: 'lr', 7: 'lr'},
                            'NextFPmap': {0: 'u', 1: 'r', 2: 'd', 3: 'd', 4: 'l', 5: 'u', 6: 'r', 7: 'l'}}
```
The dataset is then randomly sampled from these scenarios for any number of times (number_of_problems).

However, your eight scenarios only cover some possible combinations. Specifically, the up/down (`'ud'`) choice combination is not presented in any trial. Could you please clarify why this combination is not included in the scenarios? Also, you have referred to the file `MazeMetadata.py`, which is not in this repo. Where can I find this file?

**Comment by 8erberg** [comment]
Hi @nshervt -- thank you for your question!

That is correct. We explain more on the details of the task in the paper, see 'Methods: Task paradigm' (https://www.nature.com/articles/s42256-023-00748-9#Sec9).

In essence, for one of the control analysis described in the supplementary materials, we vary the task difficulty. The harder task used for additional controls uses all combinations and the baseline is a reduced set. There was no particular logic behind choosing this specific subset of trials.

You are correct, MazeMetadata.py is not included here -- this was actually just a helper line for me during development and arguably could have been deleted here to avoid confusion. As the paper above outlined, the task here is essentially a simplified version of a multistep task which we use in an experiment with non-human primates. MazeMetadata.py is the file which describes the full multistep experiment in primates and the line in the docstring is a note of how I extracted the specific set of trials from the full monkey experiment. We hopefully will have a preprint with the full monkey experiment online within the first half of 2024 but if it is relevant for your ongoing work, I am happy to share the full outline of the task with you already! 

I hope this answers your question -- happy to add details to aspects which remain unclear!
